# Generated by Django 4.0.3 on 2022-03-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estilo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musico', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banda', models.CharField(max_length=1000)),
                ('numero_integrantes', models.IntegerField(default=0)),
                ('numero_musicas', models.IntegerField(default=0)),
                ('estilo', models.ManyToManyField(to='music.estilomusical')),
                ('musicos', models.ManyToManyField(to='music.musico')),
            ],
        ),
    ]
